CREATE TABLE users (
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	passwd VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL,
	admin bool,
	session text NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  	updated TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  	CONSTRAINT PKC_id PRIMARY KEY(id),
	CONSTRAINT UC_name UNIQUE(name),
	CONSTRAINT UC_email UNIQUE(email)
);