CREATE TABLE users (
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	passwd VARCHAR(60) NOT NULL,
	email VARCHAR(255) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  	updated TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  	CONSTRAINT PKC_id PRIMARY KEY(id),
	CONSTRAINT UC_name UNIQUE(name),
	CONSTRAINT UC_email UNIQUE(email)
);

CREATE TABLE pages (
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	lang VARCHAR(20) NOT NULL,
	description text,
	keywords text,
	inhalt longtext,
	anmerkungen text,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  	updated TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  	CONSTRAINT PKC_id PRIMARY KEY(id),
	CONSTRAINT UC_page UNIQUE(name, lang)
);

CREATE TABLE adminAccounts (
	id INT NOT NULL AUTO_INCREMENT,
	session INT NOT NULL,
	email_SHA VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  	updated TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  	CONSTRAINT PKC_id PRIMARY KEY(id)
);
