CREATE TABLE users (
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
	PASSWD VARCHAR(60) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  	UPDATED TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP 

  	CONSTRAINT PKC_Id PRIMARY KEY(ID)
	CONSTRAINT UC_User UNIQUE(NAME, EMAIL),
);